/* Bar functionality */
#include "bar_indicators.h"
#include "bar_tagicons.h"
#include "bar.h"

#include "bar_ltsymbol.h"
#include "bar_status.h"
#include "bar_status2d.h"
#include "bar_statusbutton.h"
#include "bar_statuscmd.h"
#include "bar_winicon.h"
#include "bar_tags.h"
#include "bar_tagpreview.h"
#include "bar_systray.h"

/* Other patches */
#include "attachx.h"
#include "cfacts.h"
#include "cyclelayouts.h"
#include "distributetags.h"
#include "dragcfact.h"
#include "dragmfact.h"
#include "dwmc.h"
#include "focusfollowmouse.h"
#include "movestack.h"
#include "restartsig.h"
#include "scratchpad.h"
#include "scratchpad_alt_1.h"
#include "shift.h"
#include "shiftboth.h"
#include "shifttag.h"
#include "shifttagclients.h"
#include "shiftview.h"
#include "shiftviewclients.h"
#ifdef XINERAMA
#include "sortscreens.h"
#endif // XINERAMA
#include "swallow.h"
#include "togglefullscreen.h"
#include "vanitygaps.h"
#include "warp.h"
/* Layouts */
#include "layout_bstack.h"
#include "layout_bstackhoriz.h"
#include "layout_centeredmaster.h"
#include "layout_centeredfloatingmaster.h"
#include "layout_columns.h"
#include "layout_deck.h"
#include "layout_fibonacci.h"
#include "layout_grid.h"
#include "layout_horizgrid.h"
#include "layout_nrowgrid.h"
#include "layout_tile.h"

