#!/bin/bash
#  ╔╗ ╔═╗╔═╗╦ ╦╔╦╗  - Ahsan041
#  ╠╩╗╚═╗╠═╝║║║║║║  - https://github.com/zielOS/bspwm-desktop-environment
#  ╚═╝╚═╝╩  ╚╩╝╩ ╩  - ahsanur041@proton.me


#  ┬┌┬┐┌─┐┌─┐┬─┐┌┬┐┌─┐┌┐┌┌┬┐  ┬  ┬┌─┐┬─┐┬┌─┐┌┐ ┬  ┌─┐┌─┐
#  ││││├─┘│ │├┬┘ │ ├─┤│││ │   └┐┌┘├─┤├┬┘│├─┤├┴┐│  ├┤ └─┐
#  ┴┴ ┴┴  └─┘┴└─ ┴ ┴ ┴┘└┘ ┴    └┘ ┴ ┴┴└─┴┴ ┴└─┘┴─┘└─┘└─┘

export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export GDK_SCALE=1.8
export GDK_DPI_SCALE=1.5
export ELM_SCALE=1.5
export QT_QPA_PLATFORMTHEME=qt5ct
export PATH=$PATH:$HOME/.cargo/bin
export PATH=$PATH:$HOME/.local/bin
export PATH=$PATH:$HOME/.config/emacs/bin
export PATH=$PATH:$HOME/.npm-global/bin
export PATH=$PATH:/usr/local/texlive/2023/bin/x86_64-linux
export MANPATH=$MANPATH:/usr/local/texlive/2023/texmf-dist/doc/man
export INFOPATH=$INFOPATH/usr/local/texlive/2023/texmf-dist/doc/infoexport

processes=("bspc" "picom" "dunst" "eww" "gammastep" "polkit-gnome-authentication-agent-1" "bspswallow" "xrandr" "sxhkd")

for process in "${processes[@]}"; do
if pidof -q "$process"; then
  pkill -9 -x "$process" > /dev/null; sleep 0.1
fi
done

pgrep -x sxhkd > /dev/null || sxhkd -c $HOME/.config/bspwm/sxhkdrc &


#  ┬ ┬┌─┐┬─┐┬┌─┌─┐┌─┐┌─┐┌─┐┌─┐┌─┐
#  ││││ │├┬┘├┴┐└─┐├─┘├─┤│  ├┤ └─┐
#  └┴┘└─┘┴└─┴ ┴└─┘┴  ┴ ┴└─┘└─┘└─┘

bspc monitor DP-0 -d 1 2 3 4 5 6 
bspc monitor DP-2 -d 1 2 3 4 5 6 
bspc monitor DP-4 -d 1 2 3 4 5 6 

#  ┌┐ ┌─┐┌─┐┬ ┬┌┬┐  ┌─┐┌─┐┌┐┌┌─┐┬┌─┐
#  ├┴┐└─┐├─┘││││││  │  │ ││││├┤ ││ ┬
#  └─┘└─┘┴  └┴┘┴ ┴  └─┘└─┘┘└┘└  ┴└─┘

bspc config single_monocle           true
bspc config borderless_monocle       false
bspc config gapless_monocle          false
bspc config automatic_scheme         alternate
bspc config initial_polarity         second_child

bspc config focus_follows_pointer    true
bspc config pointer_follows_focus    true
bspc config pointer_motion_interval  5
bspc config pointer_modifier         mod4 
bspc config pointer_action1          move 
bspc config pointer_action2          resize_side 
bspc config pointer_action3          resize_corner

bspc config border_width             3
bspc config window_gap               12
bspc config split_ratio              0.50
bspc config top_padding              3
bspc config bottom_padding           2
bspc config focused_border_color     "#B4BEFE"
bspc config normal_border_color      "#11111B"
bspc config active_border_color      "#11111B"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a Mullvad VPN state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Emacs state=tiled
bspc rule -a kitty-float state=floating
bspc rule -a tsp state=floating
bspc rule -a tsp2 state=floating 
bspc rule -a ranger state=floating
bspc rule -a vifm state=floating
bspc rule -a lvim state=floating



#  ┬  ┌─┐┬ ┬┌┐┌┌─┐┬ ┬┌─┐┬─┐
#  │  ├─┤│ │││││  ├─┤├┤ ├┬┘
#  ┴─┘┴ ┴└─┘┘└┘└─┘┴ ┴└─┘┴└─

# Fix cursor
xsetroot -cursor_name left_ptr &

# Compositor
while pgrep -u $UID -x picom >/dev/null; do sleep 1; done
picom --config $HOME/.config/picom/picom.conf &

# Restore wallpaper
hsetroot -cover ~/.config/wallpapers/trigonometry.png &

## Run lockscreen in background


## Launch notification daemon
dwmdunst &

## Launch policykit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

xrdb merge ~/.Xresources & 

## Setup theme
#xsettingsd --config=$HOME/.config/xsettingsd/xsettingsd &

## Enable window swallowing
pidof bspswallow | bspswallow &

## Enable Power Management
xfce4-power-manager &

## Disable capslock
setxkbmap -option ctrl:nocaps &

# Fix Java problems
wmname LG3D
export _JAVA_AWT_WM_NONREPARENTING=1

## Launch apps
ckb-next &
insync start &

# setup display settings
gammastep -l 48.1:11.6 -b 0.9:0.9 -t 5700:5700 &

# Launch the bar and or eww widgets
#eww daemon &
#eww open bar & 

# Fix eww above fullscreen windows
fullscreen &

THEME='Catppuccin-Mocha-Standard-Lavender-dark'
ICONS='Papirus-Dark'
FONT='JetBrainsMono Nerd Font 13'
CURSOR='Catppuccin-Mocha-Lavender-Cursors'

SCHEMA='gsettings set org.gnome.desktop.interface'

apply_themes () {
	${SCHEMA} gtk-theme "$THEME" &
	${SCHEMA} icon-theme "$ICONS" &
	${SCHEMA} cursor-theme "$CURSOR" &
	${SCHEMA} font-name "$FONT" &
}

apply_themes
